[package]
name = "poseidon_hash_mina"
version = "0.1.0"
edition = "2024"
author = "youtpout and claude" 

[dependencies]
num-bigint = "0.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false